settings:
  title: 'OpenBMCLAPI/BMCLAPI.com部分服务状态'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '一切正常'
  notAllmonitorsOperational: '需要关注'
  monitorLabelOperational: '正在运行'
  monitorLabelNotOperational: '需要关注'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:

  - id: cloudflare-cdn
    name: Cloudflare CDN
    description: '通过Cloudflare代理的OBA服务'
    url: 'http://cloudflare.cdn.open.bmclapi.com:8080/'
    method: GET
    expectStatus: 404
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: bmclapi-com
    name: BMCLAPI.com
    description: 'BMCLAPI.com提供的OBA服务'
    url: 'http://zj-hz-1.chinanet.open.bmclapi.com:8080/'
    method: GET
    expectStatus: 404
    followRedirect: false
    linkable: false
